services:


  frontend:
    image: 26tushar01/devhive-frontend:latest
    container_name: devhive-frontend
    restart: unless-stopped
    expose:
      - "80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    image: 26tushar01/devhive-backend:latest
    container_name: devhive-server
    restart: unless-stopped
    env_file:
      - .env.prod
    expose:
      - "8080"
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    container_name: devhive-redis
    restart: unless-stopped
    command: redis-server --requirepass "${REDIS_PASS}"
    env_file:
      - .env.prod
    expose:
      - "6379"
    networks:
      - app-network

networks:
  app-network:
    external: true