spring.application.name=DevHive

#db configurations
spring.datasource.url=jdbc:postgresql://localhost:5432/DevHive_v1
spring.datasource.username=postgres
spring.datasource.password=eighteenlpa

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

