spring.application.name=DevHive

#db configurations
spring.datasource.url=jdbc:postgresql://localhost:5432/DevHive_v1
spring.datasource.username=postgres
spring.datasource.password=eighteenlpa

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.servlet.context-path=/api/v1

app.cors.allowed-origins=http://localhost:5173

jwt.secretKey=oiasguydf2whrfgiufr982634543fhjwhbfkjsg9872873rhgfhfkg

#Caching
spring.cache.type=redis
spring.data.redis.host=
spring.data.redis.port=16028
spring.data.redis.password=
spring.data.redis.ssl.enabled=false

app.redis.channel=room:code-updates