spring.application.name=DevHive

#db configurations
spring.datasource.url=jdbc:postgresql://localhost:5432/DevHive_v1
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${LOCALDB_PASS}

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.servlet.context-path=/api/v1

app.cors.allowed-origins=http://localhost:5173

jwt.secretKey=${JWT_SECRETKEY}

#Caching
spring.cache.type=redis
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASS}
spring.data.redis.ssl.enabled=false

app.redis.channel=room:code-updates