#Caching


spring.cache.type=redis
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASS}
spring.data.redis.ssl.enabled=false
app.redis.channel=room:code-updates

#Livekit (Webrtc)
livekit.api-key=${LIVEKIT_API_KEY}
livekit.api-secret=${LIVEKIT_API_SECRET}
livekit.server-url=${LIVEKIT_URL}


#db configurations
spring.datasource.url=jdbc:postgresql://postgres:5432/DevHive_v1
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${LOCALDB_PASS}

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true